service: sfn-bluegreen-deploy-demo

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello

stepFunctions:
  stateMachines:
    myStateMachine:
      useExactVersion: true
      definition:
        StartAt: Wait
        States:
          Wait:
            Type: Wait
            Seconds: 150
            Next: Hello
          Hello:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            Next: Decide
          Decide:
            Type: Choice
            Choices:
              - Variable: $
                StringEquals: ThumbsUp
                Next: Success
            Default: Failed
          Success:
            Type: Succeed
          Failed:
            Type: Fail